<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="syvolt" nsURI="http://syvolt/2.0" nsPrefix="syvolt">
  <eAnnotations source="gmf">
    <details key="foo" value="bar"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationModel">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasProperty" upperBound="-1"
        eType="#//AtomicContract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//GlobalSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalSpecification">
    <eAnnotations source="gmf.node">
      <details key="label" value="value"/>
      <details key="tool.description" value="Create a specification."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchClass" abstract="true" eSuperTypes="#//AbstractClass">
    <eAnnotations source="gmf.node">
      <details key="label" value="className"/>
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//MatchAttribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositiveMatchClass" abstract="true"
      eSuperTypes="#//MatchClass">
    <eAnnotations source="gmf.node">
      <details key="border.color" value="204,255,153"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyMatchClass" eSuperTypes="#//PositiveMatchClass">
    <eAnnotations source="gmf.node">
      <details key="tool.description" value="Match any class."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExistsMatchClass" eSuperTypes="#//PositiveMatchClass">
    <eAnnotations source="gmf.node">
      <details key="tool.description" value="Match at most one class."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreCondition">
    <eAnnotations source="gmf.node">
      <details key="foo" value="bar"/>
      <details key="tool.description" value="Match pattern. Place inside Rule."/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//MatchClass" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//MatchAssociation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchAssociation" abstract="true" eSuperTypes="#//Association">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//MatchClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//MatchClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositiveIndirectAssociation" eSuperTypes="#//MatchAssociation">
    <eAnnotations source="gmf.link">
      <details key="label" value=""/>
      <details key="style" value="dash"/>
      <details key="color" value="204,255,153"/>
      <details key="width" value="2"/>
      <details key="tool.description" value="Existing association across several containments."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeIndirectAssociation" eSuperTypes="#//MatchAssociation">
    <eAnnotations source="gmf.link">
      <details key="style" value="dash"/>
      <details key="color" value="255,61,100"/>
      <details key="width" value="2"/>
      <details key="tool.description" value="Existing association across several containments."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositiveMatchAssociation" eSuperTypes="#//MatchAssociation">
    <eAnnotations source="gmf.link">
      <details key="tool.description" value="Existing direct association."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplyClass" eSuperTypes="#//AbstractClass">
    <eAnnotations source="gmf.node">
      <details key="label" value="className"/>
      <details key="foo" value="bar"/>
      <details key="tool.description" value="Generates a class in the apply pattern."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//ApplyAttribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostCondition">
    <eAnnotations source="gmf.node">
      <details key="color" value="255,255,163"/>
      <details key="tool.description" value="Apply pattern. Place inside Rule."/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//ApplyClass" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//ApplyAssociation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplyAssociation" eSuperTypes="#//Association">
    <eAnnotations source="gmf.link">
      <details key="label" value="associationName"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="tool.description" value="Create direct association in the apply pattern."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ApplyClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ApplyClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClass" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="className"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowInheritance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="label" value="associationName"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchAttribute" eSuperTypes="#//Attribute">
    <eAnnotations source="gmf.node">
      <details key="label" value="attributeName"/>
      <details key="tool.description" value="Match an attribute."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValue" eType="#//MatchAttributeValue"
        containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplyAttribute" eSuperTypes="#//Attribute">
    <eAnnotations source="gmf.node">
      <details key="label" value="attributeName"/>
      <details key="tool.description" value="Create attribute in the apply pattern."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValue" eType="#//Term"
        containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicContract">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="tool.description" value="Create Property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="match" lowerBound="1" upperBound="-1"
        eType="#//PreCondition" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apply" lowerBound="1" eType="#//PostCondition"
        containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backwards" upperBound="-1"
        eType="#//AbstractTemporalRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRelations" upperBound="-1"
        eType="#//AbstractAttributeRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluatesBefore" eType="#//AtomicContract"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//AbstractTemporalRelation">
    <eAnnotations source="gmf.link">
      <details key="foo" value="bar"/>
      <details key="tool.description" value="Create a generator-generated restriction."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="foo" value="bar"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Term #//MatchAttributeValue">
    <eAnnotations source="gmf.node">
      <details key="label" value="value"/>
      <details key="label.icon" value="false"/>
      <details key="tool.description" value="Create a literal."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" abstract="true" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeRef" eSuperTypes="#//Ref">
    <eAnnotations source="gmf.node">
      <details key="tool.description" value="Copy attribute value."/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRef" lowerBound="1"
        eType="#//Attribute">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="width" value="2"/>
        <details key="tool.description" value="Specify source attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRef" eSuperTypes="#//Ref">
    <eAnnotations source="gmf.node">
      <details key="foo" value="bar"/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRef" lowerBound="1"
        eType="#//AbstractClass">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="width" value="2"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concat" eSuperTypes="#//Operator">
    <eAnnotations source="gmf.node">
      <details key="tool.description" value="Concatenate expressions."/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftTerm" lowerBound="1"
        eType="#//Term" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightTerm" lowerBound="1"
        eType="#//Term" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="foo" value="bar"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wildcard" eSuperTypes="#//Term">
    <eAnnotations source="gmf.node">
      <details key="tool.description" value="Match any literal."/>
      <details key="label.placement" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="attributeName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="isNull" eSuperTypes="#//MatchAttributeValue">
    <eAnnotations source="gmf.node">
      <details key="label" value="value"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchAttributeValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTemporalRelation" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="target" value="targetClass"/>
      <details key="source" value="sourceClass"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetClass" lowerBound="1"
        eType="#//ApplyClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceClass" lowerBound="1"
        eType="#//PositiveMatchClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAttributeRelation" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="target" value="targetAttribute"/>
      <details key="target.decoration" value="none"/>
      <details key="source" value="sourceAttribute"/>
      <details key="source.decoration" value="none"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAttribute" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAttribute" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchSameElements" eSuperTypes="#//MatchAssociation">
    <eAnnotations source="gmf.link">
      <details key="color" value="153,255,153"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="none"/>
      <details key="width" value="2"/>
      <details key="label.text" value="equal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplySameElements" eSuperTypes="#//ApplyAssociation">
    <eAnnotations source="gmf.link">
      <details key="color" value="153,255,153"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="none"/>
      <details key="width" value="2"/>
      <details key="label.text" value="equal"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContractReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract" eType="#//AtomicContract"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bidirectional" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Bidirectional"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Bidirectional"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implies" eSuperTypes="#//Bidirectional"/>
</ecore:EPackage>
